import { mkdir, writeFile } from "node:fs/promises";

const BROWSER_PROTOCOL_URL =
  "https://raw.githubusercontent.com/ChromeDevTools/devtools-protocol/master/json/browser_protocol.json";
const JS_PROTOCOL_URL =
  "https://raw.githubusercontent.com/ChromeDevTools/devtools-protocol/master/json/js_protocol.json";
const OUTPUT_DIR = "src/browser/data/cdp";

interface RawProtocol {
  version?: {
    major?: string;
    minor?: string;
  };
  domains?: RawDomain[];
}

interface RawDomain {
  domain: string;
  commands?: { name: string }[];
  events?: { name: string }[];
  types?: { id: string }[];
}

async function fetchJson(url: string): Promise<RawProtocol> {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Failed to fetch ${url}: ${response.status}`);
  }
  return (await response.json()) as RawProtocol;
}

function versionLabel(protocol: RawProtocol): string {
  const major = protocol.version?.major ?? "0";
  const minor = protocol.version?.minor ?? "0";
  return `${major}.${minor}`;
}

function mergeDomains(protocols: RawProtocol[]): RawDomain[] {
  const domainMap = new Map<string, RawDomain>();

  for (const protocol of protocols) {
    for (const domain of protocol.domains ?? []) {
      const existing = domainMap.get(domain.domain);
      if (!existing) {
        domainMap.set(domain.domain, {
          ...domain,
          commands: [...(domain.commands ?? [])],
          events: [...(domain.events ?? [])],
          types: [...(domain.types ?? [])]
        });
        continue;
      }

      existing.commands = [
        ...(existing.commands ?? []),
        ...(domain.commands ?? [])
      ];
      existing.events = [...(existing.events ?? []), ...(domain.events ?? [])];
      existing.types = [...(existing.types ?? []), ...(domain.types ?? [])];
    }
  }

  return [...domainMap.values()].sort((a, b) =>
    a.domain.localeCompare(b.domain)
  );
}

async function main(): Promise<void> {
  console.log("Fetching CDP protocol sources...");

  const [browserProtocol, jsProtocol] = await Promise.all([
    fetchJson(BROWSER_PROTOCOL_URL),
    fetchJson(JS_PROTOCOL_URL)
  ]);

  const mergedDomains = mergeDomains([browserProtocol, jsProtocol]);

  // Calculate totals
  const totals = mergedDomains.reduce(
    (acc, domain) => {
      acc.commands += domain.commands?.length ?? 0;
      acc.events += domain.events?.length ?? 0;
      acc.types += domain.types?.length ?? 0;
      return acc;
    },
    { domains: mergedDomains.length, commands: 0, events: 0, types: 0 }
  );

  await mkdir(OUTPUT_DIR, { recursive: true });

  // Write summary.ts with domains list and summary data
  const domainNames = mergedDomains.map((domain) => domain.domain);
  const summaryTs = `// Auto-generated by scripts/build-cdp-summary.ts

export const CDP_DOMAINS = ${JSON.stringify(domainNames)} as const;

export type CdpDomain = (typeof CDP_DOMAINS)[number];

export const CDP_SUMMARY = {
  sources: [
    { url: ${JSON.stringify(BROWSER_PROTOCOL_URL)}, version: ${JSON.stringify(versionLabel(browserProtocol))} },
    { url: ${JSON.stringify(JS_PROTOCOL_URL)}, version: ${JSON.stringify(versionLabel(jsProtocol))} }
  ],
  totals: ${JSON.stringify(totals)}
} as const;
`;

  const summaryPath = `${OUTPUT_DIR}/summary.ts`;
  await writeFile(summaryPath, summaryTs);

  console.log(`Wrote ${summaryPath}`);
  console.log(
    `Totals: ${totals.domains} domains, ${totals.commands} commands, ${totals.events} events, ${totals.types} types`
  );
}

void main().catch((error) => {
  console.error(error);
  process.exit(1);
});
