// Auto-generated by scripts/build-cdp-summary.ts

export const CDP_DOMAINS = [
  "Accessibility",
  "Animation",
  "Audits",
  "Autofill",
  "BackgroundService",
  "BluetoothEmulation",
  "Browser",
  "CacheStorage",
  "Cast",
  "Console",
  "CrashReportContext",
  "CSS",
  "Debugger",
  "DeviceAccess",
  "DeviceOrientation",
  "DOM",
  "DOMDebugger",
  "DOMSnapshot",
  "DOMStorage",
  "Emulation",
  "EventBreakpoints",
  "Extensions",
  "FedCm",
  "Fetch",
  "FileSystem",
  "HeadlessExperimental",
  "HeapProfiler",
  "IndexedDB",
  "Input",
  "Inspector",
  "IO",
  "LayerTree",
  "Log",
  "Media",
  "Memory",
  "Network",
  "Overlay",
  "Page",
  "Performance",
  "PerformanceTimeline",
  "Preload",
  "Profiler",
  "PWA",
  "Runtime",
  "Schema",
  "Security",
  "ServiceWorker",
  "SmartCardEmulation",
  "Storage",
  "SystemInfo",
  "Target",
  "Tethering",
  "Tracing",
  "WebAudio",
  "WebAuthn",
  "WebMCP"
] as const;

export type CdpDomain = (typeof CDP_DOMAINS)[number];

export const CDP_SUMMARY = {
  sources: [
    {
      url: "https://raw.githubusercontent.com/ChromeDevTools/devtools-protocol/master/json/browser_protocol.json",
      version: "1.3"
    },
    {
      url: "https://raw.githubusercontent.com/ChromeDevTools/devtools-protocol/master/json/js_protocol.json",
      version: "1.3"
    }
  ],
  totals: { domains: 56, commands: 664, events: 237, types: 608 }
} as const;
